/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stagepannels;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trainerpannels.StagiaireListe;

/**
 *
 * @author ESSAKHI Hamza
 */
public class Homestage extends javax.swing.JPanel {

    /**
     * Creates new form Homestage
     */
    public Homestage() {
        initComponents();
        showecad();
    }
public ArrayList<StageList> stgList () {
     ArrayList<StageList> stgList;
        stgList = new ArrayList<>();
        try{
             Class.forName("com.mysql.jdbc.Driver");
             Connection  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gsdba","root","");
             Statement st=con.createStatement();
             ResultSet rs = st.executeQuery("select stageprojet,serviceNom,Stagedatedebut,stagedatefin,encadrentnom,encadrentPrenom from stage,service,encadrent where  service.serviceId=stage.stageservice and stage.ecadrentstage=encadrent.encadrentId;");
             StageList ser;
             while(rs.next()){
                 ser= new StageList (rs.getString("stageprojet"),rs.getString("serviceNom"),rs.getString("encadrentnom"),rs.getString("encadrentPrenom"),rs.getDate("StageDateDebut"),rs.getDate("StageDateFin")); 
                 
                 stgList.add(ser);
             }
                 }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return stgList;
    }
     public void showecad(){
        ArrayList<StageList> list = stgList();
        DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
        Object[] row =new Object [6];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getStage();
            row[1]=list.get(i).getService();
             row[2]=list.get(i).getDe();
              row[3]=list.get(i).getFin();
               row[4]=list.get(i).getEncanom();
                row[5]=list.get(i).getEncadprenom();
                 
                 
            model.addRow(row);   
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(570, 460));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROJET", "SERVICE", "DATE DE DEBUT", "DATE DE FIN", "ENCADRENT NOM", "ENCADRENT PRENOM"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Stage project :");

        jButton1.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(280, 280, 280))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
