/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_form;
import java.awt.Color;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author abdellatifanaflous
 */
public class Lofin_Page extends javax.swing.JFrame {

    /**
     * Creates new form Lofin_Page
     */
    public Lofin_Page() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1_Username = new javax.swing.JTextField();
        jPasswordField1_Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        password = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("latifa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jTextField1_Username.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jTextField1_Username.setForeground(new java.awt.Color(150, 150, 150));
        jTextField1_Username.setText("username");
        jTextField1_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_UsernameFocusLost(evt);
            }
        });
        getContentPane().add(jTextField1_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 250, 40));

        jPasswordField1_Password.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jPasswordField1_Password.setForeground(new java.awt.Color(150, 150, 150));
        jPasswordField1_Password.setText("jPassworim");
        getContentPane().add(jPasswordField1_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 250, 40));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(100, 100, 100));
        jButton1.setText("Sign in");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 140, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(100, 100, 100));
        jButton2.setText("Quit");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 140, 40));

        password.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(100, 100, 100));
        password.setText("Show Password");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_form/last one 3.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 551, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_UsernameFocusGained
        // TODO add your handling code here:
        if(jTextField1_Username.getText().trim().toLowerCase().equals("username"))
        {
            jTextField1_Username.setText("");
            jTextField1_Username.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_jTextField1_UsernameFocusGained

    private void jTextField1_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_UsernameFocusLost
        // TODO add your handling code here:
        if(jTextField1_Username.getText().trim().equals("") || 
                jTextField1_Username.getText().trim().toLowerCase().equals("username"))
        {
            jTextField1_Username.setText("username");
            jTextField1_Username.setForeground(new Color (150,150,150));
        }
        
    }//GEN-LAST:event_jTextField1_UsernameFocusLost

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
        if (password.isSelected()){
            jPasswordField1_Password.setEchoChar((char)0);
        }else{
            jPasswordField1_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lofin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lofin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lofin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lofin_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lofin_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1_Password;
    private javax.swing.JTextField jTextField1_Username;
    private javax.swing.JCheckBox password;
    // End of variables declaration//GEN-END:variables
}
