/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home_page;

import servicepanels.Supprimerservice;
import servicepanels.Ajouterservice;
import servicepanels.Modifierservice;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import servicepanels.Homeservice;


/**
 *
 * @author latifa
 */
public class Service extends javax.swing.JPanel {

     GridBagLayout layout = new GridBagLayout();
    Supprimerservice sp;
    Ajouterservice ap;
    Modifierservice mp;
    Homeservice hs; 
    public Service() {
        initComponents();
        sp=new Supprimerservice();
        ap=new Ajouterservice();
        mp=new Modifierservice();
        hs = new Homeservice();
     
       servicepannel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
         servicepannel.add(sp,c);
        c.gridx=0;
        c.gridy=0;
        servicepannel.add(hs,c);
        c.gridx=0;
        c.gridy=0;
         servicepannel.add(ap,c);
        c.gridx=0;
        c.gridy=0;
         servicepannel.add(mp,c);
        c.gridx=0;
        c.gridy=0;
        sp.setVisible(false);
        ap.setVisible(false);
        mp.setVisible(false);
        hs.setVisible(true);
        back.setVisible(false);

                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        servicepannel = new javax.swing.JPanel();
        back = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 255));
        setPreferredSize(new java.awt.Dimension(570, 460));

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Modify");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        servicepannel.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout servicepannelLayout = new javax.swing.GroupLayout(servicepannel);
        servicepannel.setLayout(servicepannelLayout);
        servicepannelLayout.setHorizontalGroup(
            servicepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        servicepannelLayout.setVerticalGroup(
            servicepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        back.setText("Back");
        back.setMaximumSize(new java.awt.Dimension(67, 23));
        back.setMinimumSize(new java.awt.Dimension(67, 23));
        back.setPreferredSize(new java.awt.Dimension(67, 23));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(servicepannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(servicepannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        back.getAccessibleContext().setAccessibleParent(back);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        sp.setVisible(true);
        ap.setVisible(false);
        mp.setVisible(false);
         hs.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton5.setVisible(false);
        back.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        mp.setVisible(false);
        ap.setVisible(true);
        sp.setVisible(false);
         hs.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton5.setVisible(false);
        jButton5.setVisible(false);
        back.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        mp.setVisible(true);
        ap.setVisible(false);
        sp.setVisible(false);
         hs.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton5.setVisible(false);
        jButton5.setVisible(false);
        back.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        sp.setVisible(false);
        ap.setVisible(false);
        mp.setVisible(false);
        hs.setVisible(true);
        back.setVisible(false);
         jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton5.setVisible(true);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel servicepannel;
    // End of variables declaration//GEN-END:variables
}
